### ISSUE TITLE
Change command name to `adl`

### ISSUE THREAD

**Issue by gabelluardo** [gabelluardo/anime-dl#80]
I think fewer keys to type is always better, repo name will not change.

---
On `Cargo.toml`:

```toml
[[bin]]
name = "adl"
path = "src/main.rs"
```
